on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: run python
        run: ./runTests.sh
        working-directory: tests
        env:
          distribution: ../distribution.py
      - name: run perl
        run: ./runTests.sh
        working-directory: tests
        env:
          distribution: ../distribution
